Debt feature, preliminary pull request for needed classes and interfaces
OlofSjogren/GoAyo pull request #35
Opened 2020-09-15 15:05 UTC by yenanw

Co-authored-by: gabrielbrattgard <gabriel.brattgard@gmail.com>

2020-09-15 15:27 UTC, OscarSanner requested changes
I think this looks really nice good. Time effective too. Just one general question to all.

@yenanw @gabrielbrattgard @Puh00 @OlofSjogren 

Will we do this type of sub-package division?

2020-09-15 15:57 UTC, OscarSanner requested changes

2020-09-15 15:57 UTC, OscarSanner commented on app/src/main/java/com/goayo/debtify/model/debt/Ledger.java
> +}
Both team @gabrielbrattgard @yenanw  and team @OlofSjogren @Puh00 Created a ledger class.

2020-09-16 15:08 UTC, yenanw commented
I think sub-package division is quite nice. Can always refactor it later if found not suitable. @OscarSanner

2020-09-17 11:35 UTC, OscarSanner approved these changes
Looking good!

2020-09-17 11:36 UTC, merged